apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-api
  namespace: tech-challenge-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tech-challenge-api
  template:
    metadata:
      labels:
        app: tech-challenge-api
    spec:
      containers:
        - name: tech-challenge-api
          image: your-registry/tech-challenge-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: tech-challenge-config
                  key: db_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: tech-challenge-config
                  key: db_port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: tech-challenge-config
                  key: db_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-secrets
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-secrets
                  key: db_password
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20