// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/order_product_presenter_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/order_product_presenter_port.go -destination=internal/core/port/mocks/order_product_presenter_mock.go
//

// Package mock_port is a generated GoMock package.
package mock_port

import (
	reflect "reflect"

	dto "github.com/FIAP-SOAT-G20/FIAP-TechChallenge-Fase2/internal/adapter/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockOrderProductPresenter is a mock of OrderProductPresenter interface.
type MockOrderProductPresenter struct {
	ctrl     *gomock.Controller
	recorder *MockOrderProductPresenterMockRecorder
	isgomock struct{}
}

// MockOrderProductPresenterMockRecorder is the mock recorder for MockOrderProductPresenter.
type MockOrderProductPresenterMockRecorder struct {
	mock *MockOrderProductPresenter
}

// NewMockOrderProductPresenter creates a new mock instance.
func NewMockOrderProductPresenter(ctrl *gomock.Controller) *MockOrderProductPresenter {
	mock := &MockOrderProductPresenter{ctrl: ctrl}
	mock.recorder = &MockOrderProductPresenterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderProductPresenter) EXPECT() *MockOrderProductPresenterMockRecorder {
	return m.recorder
}

// Present mocks base method.
func (m *MockOrderProductPresenter) Present(pp dto.OrderProductPresenterInput) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Present", pp)
}

// Present indicates an expected call of Present.
func (mr *MockOrderProductPresenterMockRecorder) Present(pp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Present", reflect.TypeOf((*MockOrderProductPresenter)(nil).Present), pp)
}
