// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/product_presenter_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/product_presenter_port.go -destination=internal/core/port/mocks/product_presenter_mock.go
//

// Package mock_port is a generated GoMock package.
package mock_port

import (
	reflect "reflect"
	entity "tech-challenge-2-app-example/internal/core/domain/entity"
	dto "tech-challenge-2-app-example/internal/core/dto"

	gomock "go.uber.org/mock/gomock"
)

// MockProductPresenter is a mock of ProductPresenter interface.
type MockProductPresenter struct {
	ctrl     *gomock.Controller
	recorder *MockProductPresenterMockRecorder
	isgomock struct{}
}

// MockProductPresenterMockRecorder is the mock recorder for MockProductPresenter.
type MockProductPresenterMockRecorder struct {
	mock *MockProductPresenter
}

// NewMockProductPresenter creates a new mock instance.
func NewMockProductPresenter(ctrl *gomock.Controller) *MockProductPresenter {
	mock := &MockProductPresenter{ctrl: ctrl}
	mock.recorder = &MockProductPresenterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductPresenter) EXPECT() *MockProductPresenterMockRecorder {
	return m.recorder
}

// ToPaginatedResponse mocks base method.
func (m *MockProductPresenter) ToPaginatedResponse(products []*entity.Product, total int64, page, limit int) dto.PaginatedResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToPaginatedResponse", products, total, page, limit)
	ret0, _ := ret[0].(dto.PaginatedResponse)
	return ret0
}

// ToPaginatedResponse indicates an expected call of ToPaginatedResponse.
func (mr *MockProductPresenterMockRecorder) ToPaginatedResponse(products, total, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToPaginatedResponse", reflect.TypeOf((*MockProductPresenter)(nil).ToPaginatedResponse), products, total, page, limit)
}

// ToResponse mocks base method.
func (m *MockProductPresenter) ToResponse(product *entity.Product) dto.ProductResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ToResponse", product)
	ret0, _ := ret[0].(dto.ProductResponse)
	return ret0
}

// ToResponse indicates an expected call of ToResponse.
func (mr *MockProductPresenterMockRecorder) ToResponse(product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ToResponse", reflect.TypeOf((*MockProductPresenter)(nil).ToResponse), product)
}
