// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/staff_presenter_port.go

// Package mock_port is a generated GoMock package.
package mock_port

import (
	reflect "reflect"

	dto "github.com/FIAP-SOAT-G20/FIAP-TechChallenge-Fase2/internal/adapter/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockStaffPresenter is a mock of StaffPresenter interface.
type MockStaffPresenter struct {
	ctrl     *gomock.Controller
	recorder *MockStaffPresenterMockRecorder
}

// MockStaffPresenterMockRecorder is the mock recorder for MockStaffPresenter.
type MockStaffPresenterMockRecorder struct {
	mock *MockStaffPresenter
}

// NewMockStaffPresenter creates a new mock instance.
func NewMockStaffPresenter(ctrl *gomock.Controller) *MockStaffPresenter {
	mock := &MockStaffPresenter{ctrl: ctrl}
	mock.recorder = &MockStaffPresenterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStaffPresenter) EXPECT() *MockStaffPresenterMockRecorder {
	return m.recorder
}

// Present mocks base method.
func (m *MockStaffPresenter) Present(pp dto.StaffPresenterInput) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Present", pp)
}

// Present indicates an expected call of Present.
func (mr *MockStaffPresenterMockRecorder) Present(pp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Present", reflect.TypeOf((*MockStaffPresenter)(nil).Present), pp)
}
