apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-test-run
spec:
  script: 
    configMap: 
      name: k6-config
      file: script.js
  parallelism: 2  
  arguments: --out influxdb=http://influx:8086/k6